DROP TABLE IF EXISTS RATE;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USER_ROLE;

CREATE TABLE RATE (
  rateid  IDENTITY AUTO_INCREMENT  PRIMARY KEY,
  ratedescription  VARCHAR(250) NULL,
  rateexpirationdate  Date NOT NULL,
  rateeffectivedate Date NULL,
  amount DECIMAL NOT NULL,
  created_date Date NULL,
  is_deleted BOOLEAN NOT NULL
);

CREATE TABLE USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  accountnonexpired BOOLEAN NOT NULL,
  accountnonlocked BOOLEAN NOT NULL,
  credentialsnonexpired BOOLEAN NOT NULL,
  enabled BOOLEAN NOT NULL,
  is_deleted BOOLEAN NOT NULL,
  created_date Date NULL
);

CREATE TABLE ROLE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  role_name VARCHAR(250) NOT NULL,
  is_deleted BOOLEAN NOT NULL
);

CREATE TABLE USER_ROLE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  ROLE_ID  INT NOT NULL,
  USER_ID   INT NOT NULL,
  is_deleted BOOLEAN NOT NULL
);